ShortLife/upgradeRes/other/Materials/Android/L_Default.unity3d,1
ShortLife/upgradeRes/priority/lua/uLua/Lua/System/Wrap.lua,0
ShortLife/upgradeRes/priority/lua/uLua/Lua/3rd/cjson/json2lua.lua,0
ShortLife/upgradeRes/priority/lua/uLua/Lua/3rd/pblua/login_pb.lua,0
ShortLife/upgradeRes/other/things/tiles/Android/s_22.unity3d,4
ShortLife/upgradeRes/priority/lua/uLua/Lua/Logic/GameManager.lua,0
ShortLife/upgradeRes/other/things/tiles/Android/s_12.unity3d,4
ShortLife/upgradeRes/priority/lua/uLua/Lua/3rd/cjson/lua2json.lua,0
ShortLife/upgradeRes/priority/lua/uLua/Lua/System/Time.lua,0
ShortLife/upgradeRes/priority/cfg/DBCFRoleData.cfg,1
ShortLife/upgradeRes/other/things/tiles/Android/s_02.unity3d,4
ShortLife/upgradeRes/other/things/tiles/Android/stone_07.unity3d,4
ShortLife/upgradeRes/priority/lua/uLua/Lua/descriptor.lua,0
ShortLife/upgradeRes/priority/lua/ui/panel/CLLPHotWheel.lua,0
ShortLife/upgradeRes/priority/ui/panel/Android/PanelStart.unity3d,2
ShortLife/upgradeRes/priority/lua/uLua/Lua/3rd/pbc/testparser.lua,0
ShortLife/upgradeRes/priority/lua/ui/panel/CLLPStart.lua,1
ShortLife/upgradeRes/priority/cfg/DBCFCfgData.cfg,0
ShortLife/upgradeRes/priority/atlas/Android/atlasAllReal.unity3d,3
ShortLife/upgradeRes/priority/ui/other/Android/LifeBar.unity3d,2
ShortLife/upgradeRes/priority/ui/panel/Android/PanelConfirm.unity3d,2
ShortLife/upgradeRes/priority/lua/ui/cell/CLLUICellWWWProgress.lua,0
ShortLife/upgradeRes/other/texture/tileMap/Android/hexagon_new_01.unity3d,0
ShortLife/upgradeRes/other/things/tiles/Android/tree_15.unity3d,4
ShortLife/upgradeRes/other/things/tiles/Android/tile_00.unity3d,2
ShortLife/upgradeRes/other/texture/effect/baodian/Android/baodian04.unity3d,0
ShortLife/upgradeRes/other/Materials/Android/T_Default.unity3d,1
ShortLife/upgradeRes/other/things/tiles/Android/tree_09.unity3d,4
ShortLife/upgradeRes/priority/.idea/compiler.xml,0
ShortLife/upgradeRes/other/sound/Android/runLeft.unity3d,0
ShortLife/upgradeRes/priority/lua/ui/cell/CLLUICellPVEPage.lua,0
ShortLife/upgradeRes/priority/ui/panel/Android/PanelSplash.unity3d,2
ShortLife/upgradeRes/priority/lua/ui/panel/CLLPMain.lua,0
ShortLife/upgradeRes/other/things/tiles/Android/stone_06.unity3d,4
ShortLife/upgradeRes/priority/lua/ui/cell/CLLUICellServer.lua,0
ShortLife/upgradeRes/other/model/Android/hexagon_new.unity3d,0
ShortLife/upgradeRes/other/things/tiles/Android/tree_06.unity3d,4
ShortLife/upgradeRes/other/effect/Android/effect_hit.unity3d,2
ShortLife/upgradeRes/other/things/Android/Moon.unity3d,1
ShortLife/upgradeRes/priority/localization/Chinese.txt,2
ShortLife/upgradeRes/other/things/tiles/Android/stone_03.unity3d,4
ShortLife/upgradeRes/other/model/Android/dongzuo1.unity3d,0
ShortLife/upgradeRes/priority/.idea/copyright/profiles_settings.xml,0
ShortLife/upgradeRes/priority/lua/uLua/Lua/Common/define.lua,0
ShortLife/upgradeRes/priority/ui/panel/Android/PanelLoadScene.unity3d,2
ShortLife/upgradeRes/priority/lua/Role/CLLRoleSpeci_01.lua,0
ShortLife/upgradeRes/priority/lua/uLua/Lua/System/class.lua,0
ShortLife/upgradeRes/priority/lua/uLua/Lua/encoder.lua,0
ShortLife/upgradeRes/other/sound/Android/Tap.unity3d,0
ShortLife/upgradeRes/other/things/tiles/Android/s_05.unity3d,4
ShortLife/upgradeRes/other/texture/effect/baodian/Android/baodian02.unity3d,0
ShortLife/upgradeRes/other/roles/Android/Role2.unity3d,1
ShortLife/upgradeRes/priority/lua/uLua/Lua/containers.lua,0
ShortLife/upgradeRes/priority/cfg/DBCFRoleLevData.cfg,1
ShortLife/upgradeRes/priority/lua/ui/panel/CLLPOpeningPlot.lua,1
ShortLife/upgradeRes/priority/lua/ui/cell/CLLUICellStuff.lua,0
ShortLife/upgradeRes/priority/ui/panel/Android/PanelExplore.unity3d,2
ShortLife/upgradeRes/other/things/Android/Sun.unity3d,1
ShortLife/upgradeRes/other/things/Android/BegainingPlot.unity3d,5
ShortLife/upgradeRes/other/things/tiles/Android/M_water.unity3d,1
ShortLife/upgradeRes/priority/lua/uLua/Lua/System/Touch.lua,0
ShortLife/upgradeRes/other/things/tiles/Android/tree_12.unity3d,4
ShortLife/upgradeRes/other/things/tiles/Android/s_17.unity3d,4
ShortLife/upgradeRes/other/Materials/Android/sky5.unity3d,1
ShortLife/upgradeRes/priority/cfg/DBCFLevelData.cfg,3
ShortLife/upgradeRes/other/things/tiles/Android/tree_02.unity3d,4
ShortLife/upgradeRes/other/things/tiles/Android/s_07.unity3d,4
ShortLife/upgradeRes/priority/lua/public/CLLInclude.lua,2
ShortLife/upgradeRes/other/texture/effect/guangxian/Android/guangxian01.unity3d,0
ShortLife/upgradeRes/other/sound/Android/fx_save.unity3d,0
ShortLife/upgradeRes/other/things/tiles/Android/s_24.unity3d,4
ShortLife/upgradeRes/other/texture/tileMap/Android/hexagon_new_02.unity3d,0
ShortLife/upgradeRes/other/things/tiles/Android/s_14.unity3d,4
ShortLife/upgradeRes/priority/lua/net/Demo4BuildLua.lua,0
ShortLife/upgradeRes/priority/lua/ui/cell/CLLUICellLifeBar.lua,0
ShortLife/upgradeRes/priority/lua/uLua/Lua/System/Quaternion.lua,0
ShortLife/upgradeRes/other/texture/shadow/Android/guangquan.unity3d,0
ShortLife/upgradeRes/other/roles/Android/Role1.unity3d,6
ShortLife/upgradeRes/priority/lua/public/CLLPrefs.lua,0
ShortLife/upgradeRes/other/uiPic/public/Android/_empty.unity3d,0
ShortLife/upgradeRes/priority/priority.iml,0
ShortLife/upgradeRes/priority/lua/CLMainLua.lua,2
ShortLife/upgradeRes/priority/lua/ui/panel/CLLPBattle.lua,0
ShortLife/upgradeRes/priority/lua/ui/panel/CLLPLevels.lua,4
ShortLife/upgradeRes/other/things/tiles/Android/s_23.unity3d,4
ShortLife/upgradeRes/priority/lua/uLua/Lua/System/Coroutine.lua,0
ShortLife/upgradeRes/other/things/props/Android/1.unity3d,2
ShortLife/upgradeRes/other/things/tiles/Android/tree_07.unity3d,4
ShortLife/upgradeRes/other/things/tiles/Android/s_13.unity3d,4
ShortLife/upgradeRes/priority/lua/uLua/Lua/decoder.lua,0
ShortLife/upgradeRes/other/Materials/Android/O_Default.unity3d,1
ShortLife/upgradeRes/other/things/tiles/Android/tree_10.unity3d,4
ShortLife/upgradeRes/other/things/tiles/Android/stone_08.unity3d,4
ShortLife/upgradeRes/priority/lua/uLua/Lua/System/Global.lua,0
ShortLife/upgradeRes/other/Materials/Android/T_Default2.unity3d,1
ShortLife/upgradeRes/other/things/tiles/Android/s_20.unity3d,4
ShortLife/upgradeRes/other/things/tiles/Android/s_10.unity3d,4
ShortLife/upgradeRes/priority/lua/ui/panel/CLLPPackage.lua,0
ShortLife/upgradeRes/priority/lua/uLua/Lua/Logic/CtrlManager.lua,0
ShortLife/upgradeRes/priority/lua/battle/CLLBattle.lua,0
ShortLife/upgradeRes/other/things/tiles/Android/s_00.unity3d,4
ShortLife/upgradeRes/other/Materials/Android/Y_Default2.unity3d,1
ShortLife/upgradeRes/priority/cfg/DBCFBulletData.cfg,0
ShortLife/upgradeRes/priority/lua/uLua/Lua/protobuf.lua,0
ShortLife/upgradeRes/other/Materials/Android/M_Default2.unity3d,1
ShortLife/upgradeRes/priority/lua/net/CLLData.lua,1
ShortLife/upgradeRes/priority/cfg/Terrain.cfg,1
ShortLife/upgradeRes/priority/lua/ui/cell/CLLUICellLevel.lua,3
ShortLife/upgradeRes/priority/lua/uLua/Lua/3rd/cjson/util.lua,0
ShortLife/upgradeRes/priority/ui/panel/Android/PanelWWWProgress.unity3d,2
ShortLife/upgradeRes/other/Materials/Android/L_Default2.unity3d,1
ShortLife/upgradeRes/priority/lua/uLua/Lua/type_checkers.lua,0
ShortLife/upgradeRes/other/things/tiles/Android/T_Rock.unity3d,1
ShortLife/upgradeRes/priority/lua/ui/panel/CLLPSplash.lua,0
ShortLife/upgradeRes/priority/lua/uLua/Lua/3rd/pbc/parser.lua,0
ShortLife/upgradeRes/priority/ui/panel/Android/PanelBattle.unity3d,2
ShortLife/upgradeRes/other/things/tiles/Android/stone_04.unity3d,4
ShortLife/upgradeRes/priority/lua/net/optdb/CLDBGuid.lua,0
ShortLife/upgradeRes/other/texture/effect/niuquwenli/Android/baokaiwenli01.unity3d,0
ShortLife/upgradeRes/priority/lua/scene/CLLGround.lua,1
ShortLife/upgradeRes/other/things/tiles/Android/s_09.unity3d,4
ShortLife/upgradeRes/priority/lua/ui/panel/CLLPExplore.lua,1
ShortLife/upgradeRes/other/effect/Android/effect_hit2.unity3d,2
ShortLife/upgradeRes/other/things/tiles/Android/tree_04.unity3d,4
ShortLife/upgradeRes/priority/lua/toolkit/CLLCameraEffect.lua,1
ShortLife/upgradeRes/other/things/tiles/Android/stone_01.unity3d,4
ShortLife/upgradeRes/priority/lua/uLua/Lua/System/strict.lua,0
ShortLife/upgradeRes/priority/lua/uLua/Lua/System/Layer.lua,0
ShortLife/upgradeRes/priority/lua/uLua/Lua/3rd/sproto/testall.lua,0
ShortLife/upgradeRes/priority/lua/scene/CLLMapTile.lua,1
ShortLife/upgradeRes/priority/lua/uLua/Lua/text_format.lua,0
ShortLife/upgradeRes/other/things/tiles/Android/s_04.unity3d,4
ShortLife/upgradeRes/other/roles/Android/Role3.unity3d,1
ShortLife/upgradeRes/priority/lua/uLua/Lua/3rd/sproto/test.lua,0
ShortLife/upgradeRes/other/things/tiles/Android/M_tree2.unity3d,1
ShortLife/upgradeRes/priority/lua/toolkit/CLLUpdateUpgrader.lua,1
ShortLife/upgradeRes/priority/lua/ui/panel/CLLPConfirm.lua,0
ShortLife/upgradeRes/priority/lua/uLua/Lua/System/Color.lua,0
ShortLife/upgradeRes/priority/lua/uLua/Lua/System/Main.lua,0
ShortLife/upgradeRes/other/texture/shadow/Android/shadow.unity3d,0
ShortLife/upgradeRes/other/things/tiles/Android/tree_13.unity3d,4
ShortLife/upgradeRes/other/things/tiles/Android/s_18.unity3d,4
ShortLife/upgradeRes/priority/lua/uLua/Lua/Logic/LuaClass.lua,0
ShortLife/upgradeRes/priority/lua/uLua/Lua/3rd/cjson/test.lua,0
ShortLife/upgradeRes/other/things/tiles/Android/tree_03.unity3d,4
ShortLife/upgradeRes/other/things/tiles/Android/s_08.unity3d,4
ShortLife/upgradeRes/priority/lua/uLua/Lua/3rd/pbc/protobuf.lua,0
ShortLife/upgradeRes/other/sound/Android/openMenu.unity3d,0
ShortLife/upgradeRes/priority/lua/scene/CLLProp.lua,0
ShortLife/upgradeRes/priority/lua/toolkit/LuaUtl.lua,0
ShortLife/upgradeRes/priority/lua/uLua/Lua/System/Bounds.lua,0
ShortLife/upgradeRes/other/things/tiles/Android/s_15.unity3d,4
ShortLife/upgradeRes/other/sound/Android/fx_pickUp.unity3d,0
ShortLife/upgradeRes/priority/.idea/workspace.xml,20
ShortLife/upgradeRes/priority/lua/chn/CLLChn.lua,0
ShortLife/upgradeRes/other/texture/effect/Android/GlowDot.unity3d,0
ShortLife/upgradeRes/other/model/Android/Plane001.unity3d,0
ShortLife/upgradeRes/priority/lua/explore/CLLExplore.lua,12
ShortLife/upgradeRes/priority/lua/net/CLLNetDispatch.lua,0
ShortLife/upgradeRes/priority/lua/cfg/CLLDBCfg.lua,2
ShortLife/upgradeRes/other/effect/Android/PickupEffect.unity3d,2
ShortLife/upgradeRes/priority/lua/toolkit/NumEx.lua,0
ShortLife/upgradeRes/priority/lua/uLua/Lua/System/Raycast.lua,0
ShortLife/upgradeRes/priority/.idea/modules.xml,0
ShortLife/upgradeRes/priority/lua/uLua/Lua/3rd/sproto/sprotoparser.lua,0
ShortLife/upgradeRes/priority/ui/panel/Android/PanelMain.unity3d,2
ShortLife/upgradeRes/priority/lua/toolkit/LoadPreRole.lua,0
ShortLife/upgradeRes/priority/lua/Role/CLLRole.lua,3
ShortLife/upgradeRes/priority/lua/uLua/Lua/System/Vector2.lua,0
ShortLife/upgradeRes/priority/lua/uLua/Lua/eventlib.lua,0
ShortLife/upgradeRes/priority/lua/uLua/Lua/3rd/pbc/test.lua,0
ShortLife/upgradeRes/priority/lua/uLua/Lua/System/List.lua,0
ShortLife/upgradeRes/priority/lua/uLua/Lua/3rd/pbc/test2.lua,0
ShortLife/upgradeRes/priority/ui/other/Android/BuildingTitle.unity3d,2
ShortLife/upgradeRes/priority/lua/uLua/Lua/System/Vector3.lua,0
ShortLife/upgradeRes/priority/lua/ui/cell/CLLUICellHero.lua,0
ShortLife/upgradeRes/priority/cfg/DBCFPropData.cfg,0
ShortLife/upgradeRes/other/things/tiles/Android/s_21.unity3d,4
ShortLife/upgradeRes/priority/ui/panel/Android/PanelPackage.unity3d,2
ShortLife/upgradeRes/priority/lua/uLua/Lua/System/Plane.lua,0
ShortLife/upgradeRes/priority/lua/public/CLPubTypes.lua,0
ShortLife/upgradeRes/priority/lua/scene/CLLGroundOranment.lua,1
ShortLife/upgradeRes/other/things/tiles/Android/s_01.unity3d,4
ShortLife/upgradeRes/priority/lua/uLua/Lua/3rd/sproto/sproto.lua,0
ShortLife/upgradeRes/priority/lua/uLua/Lua/events.lua,0
ShortLife/upgradeRes/priority/lua/uLua/Lua/System/Ray.lua,0
ShortLife/upgradeRes/priority/lua/scene/CLLBegainingPlot.lua,1
ShortLife/upgradeRes/other/sound/Android/onhit.unity3d,0
ShortLife/upgradeRes/priority/ui/panel/Android/PanelGuid.unity3d,2
ShortLife/upgradeRes/priority/ui/panel/Android/PanelOpeningPlot.unity3d,2
ShortLife/upgradeRes/priority/lua/uLua/Lua/System/Test.lua,0
ShortLife/upgradeRes/other/model/Materials/Android/No Name.unity3d,1
ShortLife/upgradeRes/other/Materials/Android/O_Default2.unity3d,1
ShortLife/upgradeRes/priority/lua/uLua/Lua/3rd/sproto/print_r.lua,0
ShortLife/upgradeRes/priority/lua/uLua/Lua/Common/protocal.lua,0
ShortLife/upgradeRes/priority/lua/ui/panel/CLLPSet.lua,0
ShortLife/upgradeRes/other/things/props/Android/4.unity3d,2
ShortLife/upgradeRes/priority/lua/uLua/Lua/System/Math.lua,0
ShortLife/upgradeRes/priority/lua/net/CLLDataProc.lua,0
ShortLife/upgradeRes/other/things/tiles/Android/s_11.unity3d,4
ShortLife/upgradeRes/priority/lua/uLua/Lua/System/Event.lua,0
ShortLife/upgradeRes/other/things/tiles/Android/tree_08.unity3d,4
ShortLife/upgradeRes/priority/.idea/.name,0
ShortLife/upgradeRes/other/things/tiles/Android/stone_05.unity3d,4
ShortLife/upgradeRes/priority/lua/toolkit/CLLPrefabInit.lua,0
ShortLife/upgradeRes/other/things/tiles/Android/tree_05.unity3d,4
ShortLife/upgradeRes/priority/lua/cfg/CLLDBCfgTool.lua,0
ShortLife/upgradeRes/priority/lua/ui/panel/CLLPGuid.lua,0
ShortLife/upgradeRes/priority/lua/uLua/Lua/System/Set.lua,0
ShortLife/upgradeRes/other/Materials/Android/Y_Default.unity3d,1
ShortLife/upgradeRes/priority/ui/panel/Android/PanelLevels.unity3d,5
ShortLife/upgradeRes/priority/lua/ui/panel/CLLPWWWProgress.lua,0
ShortLife/upgradeRes/priority/.idea/vcs.xml,0
ShortLife/upgradeRes/other/things/tiles/Android/stone_02.unity3d,4
ShortLife/upgradeRes/other/things/tiles/Android/M_tree.unity3d,1
ShortLife/upgradeRes/other/model/Android/fangkuai.unity3d,2
ShortLife/upgradeRes/priority/lua/toolkit/CLLClickListener.lua,0
ShortLife/upgradeRes/other/model/Materials/Android/lambert1.unity3d,1
ShortLife/upgradeRes/priority/lua/ui/cell/CLLUICellPVENpc.lua,0
ShortLife/upgradeRes/other/sound/Android/runRight.unity3d,0
ShortLife/upgradeRes/other/texture/effect/yuan/Android/guanghuan01.unity3d,0
ShortLife/upgradeRes/other/texture/effect/baodian/Android/baodian03.unity3d,0
ShortLife/upgradeRes/other/texture/effect/lizi/Android/lizi01.unity3d,0
ShortLife/upgradeRes/other/things/tiles/Android/tree_14.unity3d,4
ShortLife/upgradeRes/other/things/tiles/Android/s_19.unity3d,4
ShortLife/upgradeRes/priority/lua/Role/CLLRoleSpeci_02.lua,0
ShortLife/upgradeRes/other/Materials/Android/sky7.unity3d,1
ShortLife/upgradeRes/priority/lua/ui/panel/CLLPBackplate.lua,0
ShortLife/upgradeRes/priority/ui/panel/Android/PanelHotWheel.unity3d,2
ShortLife/upgradeRes/other/sound/Android/Coolape.unity3d,0
ShortLife/upgradeRes/priority/lua/uLua/Lua/Common/functions.lua,0
ShortLife/upgradeRes/priority/.idea/misc.xml,1
ShortLife/upgradeRes/other/things/Android/line.unity3d,2
ShortLife/upgradeRes/priority/ui/panel/Android/PanelBackplate.unity3d,2
ShortLife/upgradeRes/other/things/tiles/Android/tree_11.unity3d,4
ShortLife/upgradeRes/other/things/tiles/Android/s_16.unity3d,4
ShortLife/upgradeRes/other/texture/Android/empty.unity3d,0
ShortLife/upgradeRes/priority/ui/panel/Android/PanelSet.unity3d,2
ShortLife/upgradeRes/other/things/tiles/Android/tree_01.unity3d,4
ShortLife/upgradeRes/other/things/tiles/Android/s_06.unity3d,4
ShortLife/upgradeRes/priority/lua/scene/CLLScene.lua,6
ShortLife/upgradeRes/priority/lua/chn/ChnNetHandle.lua,0
ShortLife/upgradeRes/other/things/tiles/Android/T_Rock2.unity3d,1
ShortLife/upgradeRes/priority/lua/uLua/Lua/listener.lua,0
ShortLife/upgradeRes/priority/lua/uLua/Lua/wire_format.lua,0
ShortLife/upgradeRes/priority/lua/toolkit/CLLVerManager.lua,0
ShortLife/upgradeRes/other/roles/Android/Role4.unity3d,1
ShortLife/upgradeRes/priority/ui/panel/Android/PanelMask4Panel.unity3d,2
ShortLife/upgradeRes/priority/lua/uLua/Lua/System/Vector4.lua,0
ShortLife/upgradeRes/other/things/tiles/Android/s_03.unity3d,4
ShortLife/upgradeRes/other/model/Materials/Android/01 - Default.unity3d,1
ShortLife/upgradeRes/priority/lua/net/CLLDB.lua,0
ShortLife/upgradeRes/priority/lua/ui/panel/CLLPLoadScene.lua,5
ShortLife/upgradeRes/priority/lua/uLua/Lua/System/Timer.lua,0
ShortLife/upgradeRes/priority/lua/uLua/Lua/3rd/sproto/testrpc.lua,0
ShortLife/upgradeRes/priority/lua/toolkit/CLLUINode.lua,0
ShortLife/upgradeRes/priority/lua/uLua/Lua/Logic/Network.lua,0
ShortLife/upgradeRes/other/Materials/Android/M_Default.unity3d,1
ShortLife/upgradeRes/other/texture/tileMap/Android/liubiankuang.unity3d,0
